### ISSUE TITLE
No GND on C8,C9,C10

### ISSUE THREAD

**Issue by ojaksch** [SukkoPera/OpenVideoModulator#2]
I've ordered a set of five from pcbway for my own projects. As U1 and J2 are still in delivery I already soldered all other parts.
While waiting for the U1's and J2's I've checked the pcb's for continuity but I'm missing GND at all elco's/cathode. GND **is** available at the small holes beside the elco's but not at any cathode of C8,C9 and C10.
Is this an issue by you or maybe by pcbway?

**Comment by SukkoPera** [comment]
Those points are NOT connected to ground. Look at the schematics and you'll understand ;).

**Comment by ojaksch** [comment]
Ah, yes, I see. I think I was trapped by the doublelayered and doublesided pcb with encrypted gerbers - and haven't realized the presence of the kicad file. All is good. Sorry for making any noise :)
Thanks for sharing this project! I'm curious for the video output of my CPC464...
