### ISSUE TITLE
 the image that comes out is black and white, distorted and jumpy. 

### ISSUE THREAD

**Issue by Cyrus331** [SukkoPera/OpenVideoModulator#4]
Hello, I grafted this module to the RGB output terminal of PCENGINE. The crystal oscillator has been changed to NTSC and the jumper has been connected to NTSC, but the image that comes out is black and white, distorted and jumpy. I don’t know what the problem is.

It is normal for RGB signals to be output to the TV
![微信截图_20231103114242](https://github.com/SukkoPera/OpenVideoModulator/assets/98383215/68d03614-b119-43c3-be21-9d0026c9d942)

**Comment by SukkoPera** [comment]
It's very hard to say. First of all it seems that you have redesigned the board in a different software package and you could have made errors in that. Please double check that the schematics match perfectly.

Apart from that, if you have bought your AD724 chips from China, they might be bad, I know that are batches around that do not let the crystal start to oscillate properly (or maybe they need a particular crystal, I really don't know, sometimes just touching the crystal makes it work correctly.

Also make sure you have a 10/100 uF cap on the power lines (C6/7 on my board).

I don't know what else to suggest, I guarantee that my original board works correctly and I know that other people have derived working designs from it.
